### PR TITLE
✨ feat: Support for enabling the blog module in the website

### PR DESCRIPTION
**Pull request by samzong**
- add top folder `blog`
- the sample blog in blog/2024-12-18-support-blog-post/index.md
- by default, blogs sorted by time.

### CODE REVIEW

**Comment by wawa0210** [comment]
Does the blog support multiple languages?

**Comment by samzong** [comment]
> Does the blog support multiple languages?

Yes. Open the PR Preview https://deploy-preview-17--project-hami.netlify.app/

switch Language, and you will see the chinese version.

image

**Comment by windsonsea** [comment]
/lgtm

The preview looks good.

**Pull request merged**
